### ISSUE TITLE
Setup seems not to work

### ISSUE THREAD

**Issue by b-kaiser** [strawpants/kanboard_taskwarrior#1]
Hi!

This seems like a really cool project, and I was trying to get it running. Unfortunately, I failed. I used `python3.10` and the latest `kanboard` release. On the webserver I use `PHP 8.1`. I did not really set up a database, but the web provider seems to have set it up already and kanboard worked out of te box. Maybe the issues are related to the last fact, and in this case, I am sorry for bothering you.

## Leaving assigne whose tasks need to be synced empty raises an invalid input error
I tried the following with both, an admin account and not an admin account, resulting in the same error message:
```
$ tasksync.py -c test
Project mapping test does not exist yet, create a new mapping (y/n)? [y]: y
Enter Kanboard serveraddress: mypersonalkanboardinstance.de
Enter your Kanboard username: myvalidusername
Enter personal Kanboard API Token (create in Kanboard under My profile -> API): ************************************
Enter assignee whos task need to be synced (leave empty for getting all tasks): 
Traceback (most recent call last):
  File "************/.local/bin/tasksync.py", line 111, in <module>
    main(sys.argv)
  File "************/.local/bin/tasksync.py", line 86, in main
    conn.config(args.project)
  File "************/.local/lib/python3.10/site-packages/kanboard_taskwarrior/db.py", line 189, in config
    config=runConfig(projectname,projconf)
  File "************/.local/lib/python3.10/site-packages/kanboard_taskwarrior/config.py", line 120, in runConfig
    config[ky]=prompt(val[0],getDefault(projconf,ky,val[1]))
  File "************/.local/lib/python3.10/site-packages/kanboard_taskwarrior/config.py", line 30, in prompt
    raise ValueError("Invalid input")
ValueError: Invalid input
```

## jsonrpc.php is not reachable
This one might be related to me not setting up the database correctly. However, as mentioned kanboard seems to work properly. I get the followin error message:
```
$ tasksync.py -c test 
Project mapping test does not exist yet, create a new mapping (y/n)? [y]: y
Enter Kanboard serveraddress: mypersonalkanboardinstance.de
Enter your Kanboard username: myvalidusername
Enter personal Kanboard API Token (create in Kanboard under My profile -> API): ************************
Enter assignee whos task need to be synced (leave empty for getting all tasks): myvalidusername
Whether to apply 'task sync' (sync with taskd server) before doing the syncing operation (y/n) [n]: n
tasksync-WARNING:Kanboard server https://mypersonalkanboardinstance.de/jsonrpc.php is not reachable, skipping
Traceback (most recent call last):
  File "************/.local/bin/tasksync.py", line 111, in <module>
    main(sys.argv)
  File "************.local/bin/tasksync.py", line 86, in main
    conn.config(args.project)
  File "************/.local/lib/python3.10/site-packages/kanboard_taskwarrior/db.py", line 189, in config
    config=runConfig(projectname,projconf)
  File "************/.local/lib/python3.10/site-packages/kanboard_taskwarrior/config.py", line 132, in runConfig
    proj=kbclnt.getProjectByName(name=project)
AttributeError: 'NoneType' object has no attribute 'getProjectByName'
```
If I type in `mypersonalkanboardinstance.de/jsonrpc.php` in a webbrowser (`firefox`) I get the following:
![image](https://github.com/strawpants/kanboard_taskwarrior/assets/75486170/b1441f3a-6b4f-4757-a528-abb9db86a552)

**Comment by strawpants** [comment]
thanks I'll look into  it. I suspect the parse error  on jsonrpc.php is just an indication that no arguments were supplied though, and is therefore not the problem. I get the same from my instance, and it's seems to work here. 

What kanboard versions are you using? (both server and local python module?)

**Comment by strawpants** [comment]
Maybe I misunderstood. Does the Kanboard project 'test' already exists on your server? It needs to be defined there because it uses the existing  columns and swimlanes etc from kanboard to determine the mapping to taskwarrior. I may have to add a less cryptic error message to make this clear obviously.

So can you try to create a simple project on your kanboard server and then try to configure a mapping?
