### ISSUE TITLE
Setup instructions lack requirements

### ISSUE THREAD

**Issue by DDzwiedziu** [strawpants/kanboard_taskwarrior#3]
As this is not my first Python Dependency Rodeo I can manage those dependencies. Yet I would be nice if they were included in the instructions. 

Especially that you have to do them one by one if not familiarized with the software.
First run
```
❯ ./tasksync.py -c Taskwarrior_Kanboard
Traceback (most recent call last):
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/./tasksync.py", line 5, in <module>
    from kanboard_taskwarrior.db import DbConnector
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/kanboard_taskwarrior/db.py", line 8, in <module>
    from kanboard_taskwarrior.config import runConfig,configUDA
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/kanboard_taskwarrior/config.py", line 4, in <module>
    from kanboard_taskwarrior.taskmap import getVtags,colkey,catkey,swimkey
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/kanboard_taskwarrior/taskmap.py", line 6, in <module>
    from kanboard import ClientError
ModuleNotFoundError: No module named 'kanboard'
```

`apt install python3-kanboard` & retry:

```
❯ ./tasksync.py -c Taskwarrior_Kanboard
Traceback (most recent call last):
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/./tasksync.py", line 5, in <module>
    from kanboard_taskwarrior.db import DbConnector
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/kanboard_taskwarrior/db.py", line 8, in <module>
    from kanboard_taskwarrior.config import runConfig,configUDA
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/kanboard_taskwarrior/config.py", line 4, in <module>
    from kanboard_taskwarrior.taskmap import getVtags,colkey,catkey,swimkey
  File "/home/dzwiedziu/Software/gitted/kanboard_taskwarrior/kanboard_taskwarrior/taskmap.py", line 7, in <module>
    from tasklib import Task
ModuleNotFoundError: No module named 'tasklib'
```

`apt install python3-tasklib` and still this doesn't lead to a successful run, but that's for another ticket.

Edit: maybe not another ticket, because the design, AFAIS, is to have the DB in `~/.task`, which is not the location for me. So I could probably patch something in for now.

**Comment by strawpants** [comment]
Thanks for your feedback. Although I'm still using this on a daily basis, I'm not very active in its development, so it will probably remain a niche tool for those interested. 
That being said, I've added (see 9520379967e5f523ff05f80f8b3dbb0d9d62598c) a simple requirements.txt file and an option to specify a database path in a non-default location. 

More step-by-step instructions to setup a connection may follow at some stage, so I'll leave this issue open for now.
